name: Katalon Github Action Develop Branch
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]


jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          repository: farizagati/katalon-web-cura
          
      - name: Katalon Studio Github Action
        uses: katalon-studio/katalon-studio-github-action@v3.0
        with:
          version: '8.6.8'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -browserType=Chrome -retry=0 -testSuitePath="Test Suites/Login/TS_Login" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'
