name: CI-trial
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]


jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          repository: farizagati/katalon-web-cura

      - name: List Files
        run: |
          dir
          echo %cd%
