name: Katalon Studio Test (Develop)
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.1

    - name: Set Up Katalon Studio
      uses: farizagati/katalon-web-cura@master
      with:
        version: '8.6.8'
        projectPath: '${{ github.workspace }}'
        args: '-noSplash -retry=0 -testSuitePath="Test Suites/Login/TS_Login" -executionProfile="default" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'
        
